solon.app:
  name: powerjob-solon
  group: demo

solon.cloud.powerjob:
  server: 127.0.0.1:7700
  password: powerjob123
  job:
    port: 28888
    protocol: akka
    storeStrategy: disk
    maxResultLength: 4096
    maxAppendedWfContextLength: 4096