solon.app:
  name: demoapp
  group: demo

solon.output.meta: 1

test.db1:
  config: |
    mode:
      type: Standalone
      repository:
        type: JDBC
    dataSources:
      ds_1:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
        username: root
        password: 123456
      ds_2:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
        username: root
        password: 123456
    rules:
      - !READWRITE_SPLITTING
        dataSources:
          readwrite_ds:
            staticStrategy:
              writeDataSourceName: ds_1
              readDataSourceNames:
                - ds_2
            loadBalancerName: random
        loadBalancers:
          random:
            type: RANDOM
    props:
      sql-show: true
