solon.powerjob:
  # Whether to enable PowerJob Worker, default is true
  enabled: true
  # Address of PowerJob-server node(s). Ip:port or domain. Multiple addresses should be separated with comma.
  serverAddress: 127.0.0.1:7700
  # Application name, used for grouping applications. Recommend to set the same value as project name.
  appName: powerjob-solon
  # If use PowerjobClient to submit a job, you need to set this property.
  password: powerjob123
  # Transport port, default is 27777
  port: 28888
  # transport protocol between server and worker
  protocol: akka
  # Store strategy of H2 database. disk or memory. Default value is disk.
  storeStrategy: disk
  # Max length of result. Results that are longer than the value will be truncated.
  maxResultLength: 4096
  # Max length of appended workflow context . Appended workflow context value that is longer than the value will be ignore.
  maxAppendedWfContextLength: 4096