
server.port: 8081

solon.app:
  name: demoapp
  group: demo

solon.cloud.local:
  discovery:
    service:
      hellorpc:
        - tcp://localhost:28081

solon.cloud.opentracing:
  server: "localhost:6831"


#solon.logging.logger:
#  "io.jaegertracing.*":
#    level: WARN
#  "org.noear.*":
#    level: INFO