
server.port: 8081

solon.app:
  name: demoapp
  group: demo

solon.cloud.local:
  discovery:
    service:
      hellorpc:
        - tcp://localhost:28081

solon.cloud.opentracing:
  server: "udp://localhost:6831"
  trace:
    enable: true                    #是否启用（默认：true）
    exclude: "/healthz,/_run/check/" #排除路径

