solon.app:
  namespace: test
  group: demo       #配置服务使用的默认组
  name: helloproducer    #发现服务使用的应用名

solon.cloud.aliyun.ons:
  server: "xxx.cn-hangzhou.rmq.aliyuncs.com:8080"   #rocketmq服务地址
  event:
    accessKey: LTAI5tQTngx***
    secretKey: S7Sqo88j7Jc6qk7pZ***
