

demo1.cache:
  driverType: "redis" #驱动类型
  keyHeader: "demo" #默认为 ${solon.app.name} ，可不配置
  defSeconds: 30 #默认为 30，可不配置
  server: "localhost:6379"
  db: 0 #默认为 0，可不配置
  password: ""
  maxTotaol: 200 #默认为 200，可不配