server.port: 8011

dubbo:
  application:
    name: hello
    owner: noear
  registry:
    address: nacos://localhost:8848


# 记录器级别的配置示例
solon.logging.logger:
  "root": #默认记录器配置
    level: INFO
  "com.alibaba": #包名
    level: WARN