server.port: 8085

solon.app:
  group: demo
  name: helloapi    #发现服务使用的应用名（在Demo，将被NimaClient引用）

solon.cloud.etcd:
  server: "localhost:2379"

solon.logging.logger:
  "org.apache.etcd.*":
    level: "WARN"