server.port: 7112

solon.app:
  namespace: test
  group: demo
  name: helloapi    #发现服务使用的应用名（在Demo，将被NimaClient引用）

solon.cloud.polaris:
  username: polaris        #polaris链接账号
  password: polaris        #polaris链接密码
  config:
    server: localhost:8093   #polaris配置服务地址
  discovery:
    server: localhost:8091   #polaris发现服务地址


#需要更复杂的配置，请通过资源 resources/polaris.yml 进行配置
#具体参考：https://github.com/polarismesh/polaris-java/blob/main/polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml