
solon.app:
  group: demo
  name: demoapp

#solon.env: cloud
solon.env: single

solon.logging.appender:
  console:
    level: "INFO"

solon.logging.logger:
  "org.eclipse.jetty":
    level: "WARN"
  "com.zaxxer.hikari":
    level: "WARN"

