solon.app:
    name: demoapp
    group: demo

solon.output.meta: 1

test.db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

test.db2:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456


#默认
mybatis.db1:
    typeAliases:    #支持包名 或 类名（.class 结尾）
        - "demo4022.model"
    mappers:        #支持包名 或 类名（.class 结尾）或 xml（.xml结尾 或 *.xml 结尾）
        - "demo4022.dso.mapper.AppxMapper.class"
    configuration:
        cacheEnabled: false
        mapUnderscoreToCamelCase: true


#mybatis.plugin:
#    - pagehelper:
#        class: com.github.pagehelper.PageHelper
#        dialect: mysql
#        rowBoundsWithCount: true


#再定义个新配置
mybatis.db2:
    typeAliases:
        - "demo4022.model"
    mappers:
        - "demo4022.dso.mapper.Appx2Mapper.class"

#分页组件的配置
sqlhelper:
    mybatis:
        instrumentor:
            dialect: "mysql"
            cache-instrumented-sql: true
            subquery-paging-start-flag: "[PAGING_StART]"
            subquery-paging-end-flag: "[PAGING_END]"
        pagination:
            count: true
            default-page-size: 10
            use-last-page-if-page-no-out: true
            count-suffix: _COUNT