solon.app:
    name: demoapp
    group: demo

solon.output.meta: 1

test.db1:
    schema: rock
    jdbcUrl: jdbc:mysql://localhost:3306/rock?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#默认
mybatis.db1:
    typeAliases:    #支持包名 或 类名（.class 结尾）
        - "demo4031.model"
    mappers:        #支持包名 或 类名（.class 结尾）或 xml（.xml结尾 或 *.xml 结尾）
        - "demo4031.dso.mapper"
    configuration:
        cacheEnabled: false
        mapUnderscoreToCamelCase: true
        logImpl: org.apache.ibatis.logging.nologging.NoLoggingImpl
    globalConfig:
        banner: false
        metaObjectHandler: "demo4031.dso.MetaObjectHandlerImpl"
        dbConfig:
            logicDeleteField: "deleted"
            logicDeleteValue: "2"
